from fastapi import APIRouter, HTTPException
from typing import List

router = APIRouter(
    prefix="/sapientia/catalogos",
    tags=["Catálogos Sapientia (Mock)"]
)

# Datos estáticos mock
CAMPUS = ["Campus Asunción", "Campus Alto Paraná", "Campus Guairá"]
FACULTADES = ["Ciencias y Tecnología", "Ciencias Jurídicas", "Ciencias Contables", "Filosofía", "Ciencias de la Salud"]
DEPARTAMENTOS = [
    "Arquitectura", "Análisis de Sistemas", "Ingeniería Electrónica e Informática",
    "Ingeniería Civil, Industrial y Ambiental", "Diseño Gráfico e Industrial"
]
CARRERAS = ["Ingeniería Informática", "Ingeniería Civil", "Arquitectura", "Diseño Gráfico"] # Placeholder simple
DOCENTES = ["Juan Pérez", "María González", "Carlos López"]

# Lista larga de asignaturas
ASIGNATURAS_RAW = """TALLER DE COMP. Y PROY. ARQUITECTONICO 1
GEOMETRIA DESCRIPTIVA 2
DIBUJO ARQUITECTONICO 2
MATEMATICA 2
TECNOLOGIA DE LOS MATERIALES Y LA CONS. 1
HISTORIA DE LA ARQUITECTURA 1
MISTERIO CRISTIANO 1
TALLER DE COMP. Y PROY. ARQUITECTONICO 2
FÍSICA GENERAL
DIBUJO ARQUITECTONICO 3
CALCULO 1
TECNOLOGIA DE LOS MATERIALES Y LA CONS. 2
HISTORIA DE LA ARQUITECTURA 2
ANTROPOLOGIA
MISTERIO CRISTIANO 2
TALLER DE PROYECTO ARQUITECTONICO 3
MEDIOS DIGITALES 1
CÁLCULO 2
TECNOLOGIA DE LA CONSTRUCCION 3
HISTORIA DE LA ARQUITECTURA 3
SOCIOLOGIA
COMUNICACION PROFESIONAL
ANTROPOLOGIA CRISTIANA
TALLER DE PROYECTO ARQUITECTONICO 4
DISEÑO DE ESTRUCTURAS 1
INSTALACIONES SANITARIAS
TECNOLOGIA DE LA CONSTRUCCION 4
URBANISMO 1
HISTORIA DE LA ARQUITECTURA 4
MEDIOS DIGITALES 2
ETICA FUNDAMENTAL
TALLER DE PROYECTO ARQUITECTONICO 5
DISEÑO DE ESTRUCTURAS 2
URBANISMO 2
MEDIOS DIGITALES 3
PATOL. Y REHABILITACION DE LA CONST.
INSTALACIONES ELECTRICAS
TEORIA Y CRITICA DE LA ARQUITECTURA 1
ETICA PERSONAL
TALLER DE PROYECTO ARQUITECTONICO 6
PAISAJISMO 1
MEDIOS DIGITALES 4
GESTION DE OBRA Y PROYECTO 1
ACONDICIONAMIENTO BIOCLIMATICO
ÉTICA SOCIAL 1
TALLER DE PROYECTO ARQUITECTONICO 7
PAISAJISMO 2
DOCUMENTACION DE OBRA 1
GESTION DE OBRA Y PROYECTO 2
ARQUITECTURA Y MEDIO AMBIENTE
TEORIA Y CRITICA DE LA ARQUITECTURA 3
ETICA SOCIAL 2
PLANIFICACION TERRITORIAL
DOCUMENTACION DE OBRA 2
GESTION DE OBRA Y PROYECTO 3
TEORIA Y CRITICA DE LA ARQUITECTURA 4
LEGISLACION DE OBRA 1
ETICA PROFESIONAL
TALLER DE PROYECTO URBANO 2
DOCUMENTACION DE OBRA 3
AVALUACION DE INMUEBLES
PRESERVACION Y PATRIMONIO
LEGISLACION DE OBRA 2
MATEMATICA 1
INFORMATICA 1
PROGRAMACION 1
COMUNICACIÓN ORAL Y ESCRITA II
INFORMATICA 2
PROGRAMACION 2
HISTORIA DE LA CULTURA
MATEMATICA 3
INFORMATICA 3
PROGRAMACION 3
INTRODUCCIÓN A LA SOCIOLOGÍA
MATEMATICA 4
INFORMATICA 4
PROGRAMACION 4
ANTROPOLOGÍA FILOSÓFICA
INGENIERIA DEL SOFTWARE 2
ORGANIZACION 2
MATEMATICA 6
INFORMATICA 6
INFORMATICA 8
INGENIERIA DEL SOFTWARE 4
ORGANIZACION 4
TESIS
CÁLCULO 1
ALGEBRA VECTORIAL
INTRODUCCIÓN A LA ALGORITMIA
INTRODUCCIÓN A LA FÍSICA
INTRODUCCIÓN A LA INFORMÁTICA
FÍSICA 1
TEORÍA Y APLIC. DE LA INFORMÁTICA 1
ALGEBRA LINEAL
FÍSICA 2
LENGUAJES DE PROGRAMACIÓN 1
CÁLCULO 3
ECUACIONES DIFERENCIALES
TEORÍA DE CIRCUITOS 1
MATEMÁTICA PARA INFORMÁTICOS
TECNOLOGÍAS ELECTRÓNICAS
SISTEMAS DIGITALES 1
ELECTRÓNICA 1
ESTADISTICA 1
ARQUITECTURA DE SISTEMA
SISTEMAS OPERATIVOS 1
LENGUAJES DE PROGRAMACIÓN 3
PROYECTO CON MICROPROCESADORES 1
PROCESAMIENTO DIGITAL DE SEÑALES
CONTROLES AUTOMATICOS
REDES DE COMPUTADORAS 2
CÁLCULO NUMÉRICO
INGENIERIA DE SOFTWARE 1
ECONOMIA INDUSTRIAL
AUTOMATIZACIÓN
TELECOMUNICACIONES 2
TEORÍA Y APLIC. DE LA INFORMÁTICA 2
COMPLEMENTO DE INFORMATICA
PROYECTO FINAL
DIBUJO TÉCNICO
QUÍMICA GENERAL
INFORMÁTICA 1
REPRESENTACIÓN GRÁFICA 1
REPRESENTACIÓN GRÁFICA 2
DISEÑO ASISTIDO POR COMPUTADORA
MECÁNICA RACIONAL 1
MATERIALES PARA INGENIERIA INDUSTRIAL
QUÍMICA AMBIENTAL
SENSOREAMIENTO REMOTO
FÍSICA 3
ESTÁTICA 1
ECONOMIA POLITICA
TOPOGRAFIA
GEOLOGÍA
TECNOLOGÍA DE LOS MATERIALES 1
ESTADÍSTICA
RESISTENCIA DE MATERIALES 1
MATEMÁTICA APLICADA
TECNOLOGÍA DE LOS MATERIALES 2
ESTÁTICA 2
ADMINISTRACIÓN 1
GESTIÓN AMBIENTAL
HIGIENE Y SEGURIDAD INDUSTRIAL
HIDROLOGÍA SUPERFICIAL Y SUBTERRÁNEA
TRANSFERENCIAS 1
TERMODINÁMICA APLICADA
SOCIOLOGÍA AMBIENTAL 2
VÍAS DE COMUNICACIÓN 1
GEOTECNIA 1
MECÁNICA DE FLUIDOS
RESISTENCIA DE MATERIALES 2
ESTÁTICA 3
TECNOLOGÍA DE LA CONSTRUCCIÓN 1
GEOTECNIA 2
ESTRUCTURAS DE MADERA Y METÁLICAS
HIDRÁULICA APLICADA
INGENIERÍA DE MÉTODOS Y PLANTAS
ESTRUCTURAS 1
TECNOLOGÍA DE LA CONSTRUCCIÓN 2
VÍAS DE COMUNICACIÓN 2
DISEÑO MECÁNICO
INST. CONTROL DE PROC.Y AUTOMATIZACION
LOGÍSTICA INDUSTRIAL
MANTENIMIENTO INDUSTRIAL
INGENIERIA ECONÓMICA (INDUSTRIAL)
PRODUCCIÓN LIMPIA 2
TRATAMIENTO Y ABAST. DE AGUA
HIDROLOGÍA Y OBRAS HIDRÁULICAS
ESTRUCTURAS 2
HORMIGÓN PRETENSADO
TECNOLOGÍA DE LA CONSTRUCCIÓN 3
GEOTECNIA 3
ORGANIZACIÓN DE OBRAS
ESTRUCTURAS 3
INGENIERIA ECONÓMICA (CIVIL)
INSTALACIONES ELÉCTRICAS
PUENTES
INGENIERÍA LEGAL
GESTIÓN DE CALIDAD
PLANIFICACION Y GESTIÓN ESTRATÉGICA
PRODUCCION 2
TEORIA Y COMPORTAMIENTO ORGANIZACIONAL
GUARANI
TALLER DE DISEÑO 1
REPRESENTACIÓN VISUAL 1
DIBUJO TÉCNICO 1
REPRESENTACIÓN DIGITAL 1
TALLER DE MAQUETAS
MATEMÁTICAS PARA DISEÑADORES
COMUNICACIÓN ORAL Y ESCRITA 1
TALLER DE DISEÑO 2
REPRESENTACIÓN VISUAL 2
DIBUJO TÉCNICO 2
REPRESENTACIÓN DIGITAL 2
ERGONOMÍA
HISTORIA DEL DISEÑO
COMUNICACIÓN ORAL Y ESCRITA 2
TALLER DE DISEÑO 3
REPRESENTACIÓN VISUAL 3
REPRESENTACIÓN DIGITAL 3
FOTOGRAFÍA
SEMIOLOGÍA Y TEORÍA DE LA IMAGEN
TEORÍA DEL DISEÑO
MARKETING
LEGISLACIÓN
TALLER DE DISEÑO 4
TÉCNICAS DE ILUSTRACIÓN
SÍNTESIS DE LA FORMA
REPRESENTACIÓN DIGITAL 4
TECNOLOGÍA 1
GESTIÓN DE EMPRESAS
DISEÑO GRÁFICO 2
ILUSTRACION ESPECIALIZADA 2
DISEÑO TIPOGRÁFICO 2
REPRESENTACIÓN DIGITAL 6
PRODUCCIÓN AUDIOVISUAL 1
INTRO. A LA METODOLOGÍA DE LA INV.
SELECTIVA 2
DISEÑO INDUSTRIAL 2
ERGONOMÍA APLICADA
DOCUMENTACIÖN TËCNICA 2
LABORATORIO 1
TECNOLOGÍA 3
INVESTIGACIÓN APLICADA
SEMINARIO INTERDISCIPLINARIO
PROYECTO FINAL 1
PROYECTO FINAL 2"""

ASIGNATURAS = [a.strip() for a in ASIGNATURAS_RAW.split('\n') if a.strip()]

@router.get("/{tipo}", response_model=List[str])
def obtener_catalogo(tipo: str):
    if tipo == "campus":
        return CAMPUS
    elif tipo == "facultad":
        return FACULTADES
    elif tipo == "departamento":
        return DEPARTAMENTOS
    elif tipo == "carrera":
        return CARRERAS
    elif tipo == "asignatura":
        return ASIGNATURAS
    elif tipo == "docente":
        return DOCENTES
    else:
        raise HTTPException(status_code=404, detail="Tipo de catálogo no encontrado")
